import os
from dotenv import load_dotenv

load_dotenv()


class Config:
    SECRET_KEY = os.getenv("SECRET_KEY")

    MONGODB_CONNECTION_URI = os.getenv("MONGODB_CONNECTION_URI")
    DB_NAME = "iaat"
    COLLECTION_NAME = "assets"

    HOOKDECK_WEBHOOK_SECRET = os.getenv("HOOKDECK_WEBHOOK_SECRET")
    HOOKDECK_QUEUE_API_KEY_HEADER_NAME = "x-iaat-queue-api-key"
    HOOKDECK_REPLICATE_API_QUEUE_API_KEY = os.getenv(
        "HOOKDECK_REPLICATE_API_QUEUE_API_KEY"
    )
    HOOKDECK_QUEUE_AUTH_HEADERS = {}
    HOOKDECK_QUEUE_AUTH_HEADERS[HOOKDECK_QUEUE_API_KEY_HEADER_NAME] = (
        HOOKDECK_REPLICATE_API_QUEUE_API_KEY
    )
    HOOKDECK_REPLICATE_API_QUEUE_URL = os.getenv("HOOKDECK_REPLICATE_API_QUEUE_URL")
    AUDIO_WEBHOOK_URL = os.getenv("AUDIO_WEBHOOK_URL")
    EMBEDDINGS_WEBHOOK_URL = os.getenv("EMBEDDINGS_WEBHOOK_URL")
    HOOKDECK_PROJECT_API_KEY = os.getenv("HOOKDECK_PROJECT_API_KEY")

    REPLICATE_API_TOKEN = os.getenv("REPLICATE_API_TOKEN")
    REPLICATE_API_AUTH_HEADERS = {"Authorization": f"Bearer {REPLICATE_API_TOKEN}"}
    REPLICATE_WEBHOOKS_SECRET = os.getenv("REPLICATE_WEBHOOKS_SECRET")
